version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

  app:
    image: erdalnyr01/planlama-pro-api:1.0
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongo
    volumes:
      - app-data:/src
    networks:
      - app-network
    environment:
      - MONGODB_PASSWORD=
      - MONGODB_DBNAME=
      - JWT_SECRET_KEY=
      - SESSION_KEY=

volumes:
  app-data:

networks:
  app-network:
    driver: bridge
