version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "*2023*2023*"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URL: mongodb://root:example@mongo:27017/PlanlamaProDB?authSource=admin
